# dbt_project.yml
name: 'dbt_unit_testing'
version: '1.0.0'

profile: 'dbt_unit_testing'  # Assurez-vous que cela fait référence à un profil local défini dans profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_unit_testing:
    mart:
      +materialized: table
    base:
      +materialized: table

