version: 2

sources:
  - name: kata  
    database: kata 
    schema: silver
    tables:
      - name: personnes
        description: "Table contenant les informations des personnes"
      - name: voitures
        description: "Table contenant les informations des voitures"
